### PR TITLE
#167733810 A JWT Is Sent Back On Successful Registration

### PR DESCRIPTION
**Pull request by EziamakaNV**
#### What does this PR do?
This PR implements the signup functionality, enabling users to register for the service

#### Description of Task to be completed?
- Setup the user route in the server file
- Create the user file in the routes folder
- Create a user file in the controller's folder and import it for use in the route folder
- Set up the user controller to implement the signup algorithm
- Document the feature using Swagger

#### How should this be manually tested?
- Ensure node.js and postman are installed
- Clone the repository to your system
- Navigate to the just cloned repo on your command line
- Type "npm install"
- Set environment variables DATABASE_DEV(database connection url) JWT_SECRET(any secret)
- Then type "npm run start-dev"
- Once the server starts running, use postman to send a POST request to the server endpoint
/api/v1/auth/signup. The request body should contain the fields: firstName, lastName, email, and password
- On successful registration a JWT is sent in the response body with other details as well

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- #167733810

### CODE REVIEW

**Review by kingsley-einstein — APPROVED** [review]
Good job mate!

**Comment by evansinho** [comment]
Emeka nice job ,but please do  reach out to kingsley, your both features shouldn't be in different files

**Comment by evansinho** [comment]
And i also forgot to add, you did not write test for your feature :)

**Comment by codecell** [comment]
Nice job man, but an observation i have is that some route work were done in src/routes/api/users.js file, now some of the logic were kind of repeated again because there is a router.post('/users', callback) route there already, so how do we merge this to yours in the controllers folder so we dont repeat things

**Review by evansinho — COMMENTED** [review]
Emeka niceeee :)

**Review by evansinho — APPROVED** [review]

**Review by Oluwafayokemi — CHANGES_REQUESTED** [review]
Please write unit test for this feature

**Review by evansinho — APPROVED** [review]

**Comment by fegzycole** [comment]
Good job bro.

**Review by Oluwafayokemi — APPROVED** [review]

**Comment by Ileriayo** [comment]
@EziamakaNV, kindly attach screenshot of the test results.

**Pull request merged**
